### ISSUE TITLE
个人问题

### ISSUE THREAD

**Issue by StevenJack1** [lemonhu/stock-knowledge-graph#3]
您好，我想问您个个人问题，不知您方便不方便解答，就是我现在有两个实体，一个是人、一个是公司，他们之间分别有人投资公司和公司投资公司这两个关系，假设type都是invest，那么我可以把这两个都放到一个csv文件吗，之后把这个文件import到neo4j中，

**Comment by lemonhu** [comment]
据我了解，一个csv文件只能包含一种实体类型或一种关系类型，但是可以通过Neo4j的Python/Java/...接口实现实体和关系三元组的创建和写入，这种方式比较灵活，适合增量式写入，而`import`的方式适合开始时大规模创建。
